--1
CREATE TABLE TB_CATEGORY(
	NAME	VARCHAR2(10),
	USE_YN	CHAR(1) DEFAULT 'Y'
);
SELECT * FROM TB_CATEGORY;
DROP TABLE TB_CATEGORY;

-- DML DDL

CREATE TABLE MEMBER (
	MEMBER_ID	NUMBER PRIMARY KEY,
	NAME		VARCHAR2(25) NOT NULL,
	ADDRESS		VARCHAR2(100),
	CITY		VARCHAR2(30),
	PHONE		VARCHAR2(15),
	JOIN_DATE	DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE TITLE (
	TITLE_ID	NUMBER PRIMARY KEY,
	TITLE		VARCHAR2(60) NOT NULL,
	DESCRIPTION	VARCHAR2(400) NOT NULL,
	RATING		VARCHAR2(20) CHECK (RATING IN ('18가', '15가', '12가', '전체가')),
	CATEGORY	VARCHAR2(20) CHECK (CATEGORY IN ('드라마', '코미디', '액션', '아동', 'SF', '다큐멘터리')),
	RELEASE_DATE	DATE
);

CREATE TABLE TITLE_COPY (
	COPY_ID		NUMBER,
	TITLE_ID	NUMBER,
	STATUS		VARCHAR2(20) CHECK (STATUS IN ('대여가능', '파손', '대여중', '예약')) NOT NULL,
	PRIMARY KEY (COPY_ID, TITLE_ID),
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID)
);

SELECT * FROM RENTAL;

CREATE TABLE RENTAL
(BOOK_DATE DATE DEFAULT SYSDATE,
 MEMBER_ID NUMBER(10),
 COPY_ID NUMBER(10),
 TITLE_ID NUMBER(10),
 ACT_RET_DATE DATE,
 EXP_RET_DATE DATE DEFAULT SYSDATE+2,
 PRIMARY KEY(BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID),
 FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
 FOREIGN KEY(COPY_ID, TITLE_ID) REFERENCES TITLE_COPY(COPY_ID, TITLE_ID));

CREATE TABLE RESERVATION (
	RES_DATE	DATE,
	MEMBER_ID	NUMBER,
	TITLE_ID	NUMBER,
	PRIMARY KEY (RES_DATE, MEMBER_ID, TITLE_ID),
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID)
);

CREATE SEQUENCE MEMBER_ID_SEQ 
START WITH 101
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE TITLE_ID_SEQ 
START WITH 92
INCREMENT BY 1
NOCACHE;

INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, '인어공주', '인어공주설명', '전체가', '아동', '95/10/05');
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL,'매트릭스', '매트릭스설명', '15가', 'SF', '95/05/19');
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL,'에이리언', '에이리언설명', '18가', 'SF', '95/08/12');
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL,'모던타임즈', '모던타임즈설명', '전체가', '코미디', '95/07/12');
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL,'러브스토리', '러브스토리설명', '전체가', '드라마', '95/09/12');
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL,'람보', '람보설명', '18가', '액션', '95/06/01');

SELECT * FROM TITLE;
SELECT * FROM MEMBER;

INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (MEMBER_ID_SEQ.NEXTVAL, '김철수', '강남구', '서울', '899-6666', '90/03/08');
INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (MEMBER_ID_SEQ.NEXTVAL, '이영희', '서면', '부산', '355-8883', '90/03/08');
INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (MEMBER_ID_SEQ.NEXTVAL, '최진국', '동광양', '제주', '852-5764', '91/06/17');
INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (MEMBER_ID_SEQ.NEXTVAL, '민병국', '홍제동', '강릉', '559-7777', '90/04/07');
INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (MEMBER_ID_SEQ.NEXTVAL, '민병국', '전민동', '대전', '559-8741', '90/01/18');
INSERT INTO MEMBER (MEMBER_ID, NAME, ADDRESS, CITY, PHONE, JOIN_DATE)
VALUES (MEMBER_ID_SEQ.NEXTVAL, '오민수', '북구', '광주', '542-9988', '90/01/18');

INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('1', '92', '대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('1','99', '대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('2', '99', '대여중');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('3', '94', '대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('1', '95','대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('2', '95','대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('3', '95', '대여중');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('1', '96', '대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('1', '97', '대여가능');

SELECT * FROM TITLE_COPY;
SELECT * FROM RENTAL;

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, ACT_RET_DATE, EXP_RET_DATE)
VALUES (SYSDATE-3, '101', '1', '92', SYSDATE-2, SYSDATE-1);
INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE-1, '103', '2', '99', SYSDATE-3);
INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE-2, '104', '3', '95', SYSDATE);
INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, ACT_RET_DATE, EXP_RET_DATE)
VALUES (SYSDATE-4, '105', '1', '97',SYSDATE-2, SYSDATE-2);

CREATE VIEW TITLE_AVAIL AS
	SELECT	T.TITLE, TC.COPY_ID, TC.STATUS, R.EXP_RET_DATE
	FROM	TITLE_COPY TC
	JOIN	TITLE T ON (TC.TITLE_ID = T.TITLE_ID)
	JOIN	RENTAL R ON (TC.TITLE_ID = R.TITLE_ID)
	ORDER BY 1;

--8
INSERT INTO TITLE (TITLE_ID, TITLE, DESCRIPTION, RATING, CATEGORY, RELEASE_DATE)
VALUES (TITLE_ID_SEQ.NEXTVAL, '스타워즈', '스타워즈설명', '전체가', 'SF', '77/07/07');

SELECT * FROM TITLE_COPY;

INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('1', '100', '대여가능');
INSERT INTO TITLE_COPY (COPY_ID, TITLE_ID, STATUS)
VALUES ('2', '100', '대여가능');

SELECT * FROM RESERVATION;
SELECT * FROM MEMBER;

INSERT INTO RESERVATION (RES_DATE, MEMBER_ID, TITLE_ID)
VALUES (SYSDATE, '102', '100');
INSERT INTO RESERVATION (RES_DATE, MEMBER_ID, TITLE_ID)
VALUES (SYSDATE, '106', '96');

DELETE FROM RESERVATION WHERE TITLE_ID = '100';

SELECT * FROM RENTAL;

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, ACT_RET_DATE)
VALUES (SYSDATE, '102', '1', '100', SYSDATE);

UPDATE TITLE_COPY
SET STATUS = '대여중'
WHERE TITLE_ID = '100' AND COPY_ID = '1';

SELECT * FROM TITLE_AVAIL;

--9
ALTER TABLE TITLE ADD PRICE NUMBER NOT NULL;








