--1.1
SELECT	DEPARTMENT_NAME AS "학과 명"
		, CATEGORY AS 계열
FROM	TB_DEPARTMENT;
--
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
--1.2
SELECT 	DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' AS "학과별 정원" 
FROM	TB_DEPARTMENT;
--1.3
SELECT	STUDENT_NAME
FROM	TB_STUDENT
WHERE	DEPARTMENT_NO = '001'
AND		ABSENCE_YN = 'Y'
AND		STUDENT_SSN LIKE '_______2%';
--1.4
SELECT	STUDENT_NAME
FROM	TB_STUDENT
WHERE	STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');
--1.5
SELECT	DEPARTMENT_NAME, CATEGORY
FROM	TB_DEPARTMENT
WHERE	CAPACITY BETWEEN 20 AND 30; 
--1.6
SELECT	PROFESSOR_NAME
FROM	TB_PROFESSOR
WHERE	DEPARTMENT_NO IS NULL;
--1.7
SELECT	COUNT(STUDENT_NAME) AS "미등록 학생 수"
FROM	TB_STUDENT
WHERE	DEPARTMENT_NO IS NULL
--1.8
SELECT	CLASS_NO
FROM	TB_CLASS
WHERE	PREATTENDING_CLASS_NO IS NOT NULL;
--1.9
SELECT	DISTINCT CATEGORY
FROM	TB_DEPARTMENT;
--1.10
SELECT	STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM	TB_STUDENT
WHERE	EXTRACT(YEAR FROM ENTRANCE_DATE) = 2002
AND		ABSENCE_YN = 'N'
AND		STUDENT_ADDRESS LIKE '전주%';
---------------------------------------------------------------------
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;

--2.1
SELECT	STUDENT_NO AS 학번, STUDENT_NAME AS 이름, ENTRANCE_DATE AS 입학년도
FROM	TB_STUDENT
WHERE	DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE;

--2.2
SELECT	PROFESSOR_NAME, PROFESSOR_SSN
FROM	TB_PROFESSOR
WHERE	LENGTH(PROFESSOR_NAME) > 3
OR		LENGTH(PROFESSOR_NAME) < 3;

--2.3
SELECT	PROFESSOR_NAME,
		ROUND(MONTHS_BETWEEN (
                 SYSDATE,
                 TO_DATE (
                       (DECODE(SUBSTR(PROFESSOR_SSN, 8,1), '1','19','2','19','20'))
                    || SUBSTR(PROFESSOR_SSN, 1, 6), 'YYYYMMDD')) / 12) AS 나이
FROM	TB_PROFESSOR
ORDER BY 나이;

--2.4
SELECT	SUBSTR(PROFESSOR_NAME, -2)
FROM	TB_PROFESSOR

--2.5 *********
SELECT	STUDENT_NO,
		STUDENT_NAME
FROM	TB_STUDENT
WHERE	ROUND(MONTHS_BETWEEN( 
                 	ENTRANCE_DATE,
                 TO_DATE(
                       DECODE(SUBSTR(STUDENT_SSN, 8,1), '1','19','2','19','20')
                    	|| SUBSTR(STUDENT_SSN, 1, 6), 'YYYYMMDD'))
                 / 12) > 19;


SELECT * FROM TB_STUDENT;

--2.6
SELECT	TO_CHAR(TO_DATE('20201225', 'YYYYMMDD'), 'day')
FROM DUAL;

--2.7
--2.8
SELECT	STUDENT_NO, STUDENT_NAME
FROM	TB_STUDENT
WHERE	STUDENT_NO NOT LIKE 'A%';

--2.9
SELECT	ROUND(AVG(POINT), 1) AS 평점
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A517178';

--2.10
SELECT	DEPARTMENT_NO AS 학과번호, COUNT(*) AS 학생수
FROM	TB_STUDENT
GROUP BY	DEPARTMENT_NO
ORDER BY	DEPARTMENT_NO;

--2.11
SELECT	COUNT(*)
FROM	TB_STUDENT
WHERE	COACH_PROFESSOR_NO IS NULL;

--2.12
SELECT	SUBSTR(TERM_NO, 1, 4) AS 년도,
		AVG(POINT) AS "년도 별 평점"
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A112113'
GROUP BY	SUBSTR(TERM_NO, 1, 4);

--2.13
SELECT	DEPARTMENT_NO, SUM(DECODE(ABSENCE_YN, 'Y', '1', '0'))
FROM	TB_STUDENT
GROUP BY 	DEPARTMENT_NO
ORDER BY	DEPARTMENT_NO;

--2.14
SELECT STUDENT_NAME, COUNT(*)
FROM	TB_STUDENT
GROUP BY STUDENT_NAME
HAVING	COUNT(*) > 1;

--2.15 ROLL_UP쓰기
SELECT	SUBSTR(TERM_NO, 1, 4) AS 년도,
		SUBSTR(TERM_NO, 5, 2) AS 학기,
		ROUND(AVG(POINT), 1) AS 평점
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY 1;


SELECT * FROM TB_GRADE;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;




